<?php

namespace Xls;

class Fill
{
    const PATTERN_NONE = 0;
    const PATTERN_SOLID = 1;
    const PATTERN_GRAY6 = 18;
    const PATTERN_GRAY12 = 17;
    const PATTERN_GRAY25 = 4;
    const PATTERN_GRAY50 = 2;
    const PATTERN_GRAY75 = 3;
    const PATTERN_HORIZONTAL_STRIPE = 5;
    const PATTERN_VERTICAL_STRIPE = 6;
    const PATTERN_REVERSE_DIAGONAL_STRIPE = 7;
    const PATTERN_DIAGONAL_STRIPE = 8;
    const PATTERN_DIAGONAL_CROSSHATCH = 9;
    const PATTERN_THICK_DIAGONAL_CROSSHATCH = 10;
    const PATTERN_THIN_HORIZONTAL_STRIPE = 11;
    const PATTERN_THIN_VERTICAL_STRIPE = 12;
    const PATTERN_THIN_REVERSE_DIAGONAL_STRIPE = 13;
    const PATTERN_THIN_DIAGONAL_STRIPE = 14;
    const PATTERN_THIN_HORIZONTAL_CROSSHATCH = 15;
    const PATTERN_THIN_DIAGONAL_CROSSHATCH = 16;
}
